language: node_js
cache:
  directories:
  - node_modules
  - "~/.npm"
node_js:
- '12'
git:
  depth: 3
notifications:
  email:
    recipients:
    - ingecarlos.gutierrez@gmail.com
    on_success: always
    on_failure: always
deploy:
  provider: heroku
  cleanup: true
  keep-history: true
  api_key:
    secure: WdLMHcmHTXzUWOmoneGjr6qKdtMsx4/PLEpEFglOKHeyqZuJiSLbK7vu2jVKgAGSaRq5gYLUb2SmHf67aLsBmRvDgP5s0t+zIEiYqc7KpVU1Z7QG/NxL5Khj7WBjsJvEivbQ+tFuVtUu8aLkCR5fGo6XhsH1liw3DhcdRcIomSApp7Fn8ZIl3LM7OgfZVOcctptPYuXEuFprASNmZReheayQXCx3OW/bLS/59qcCL46jWRQ+iAawhLNv3N/ASAasQz+ntJqo5CI80sBOxqkqEjNR3B8+VkV2AP9V/AkeToYGWXze9lFoP3iDV0k7i7J1JtJR48KbjnQCc9rMpfelqJ3G17dDsZPu4sFIKFkfWTzdK8viGzgf5m4pNrdVNvm8ioDw6+lCTNjOaNH8qGCi8omKzaf7BdZkoTbT6vppPWdNFVEUPvbUKdFXyoxawCaifR7F1da60Sf5KnXxtkETqOo5ObHRVpH3f+FlHCKur6YxRLIFFrSS3lEbZYNmkYVZ0/z6i7kwApLtQ/TP/3aBuxcZHH+GQYmMUAddLyunhC0MQlQQ5HOs2hBKH6nu5n8tE513U51ir85jywC30H9E0b76w6RLw1YvhM72/fVEKRMeR1ZvWcjrU+4s962JB0eikaHwea7+l+eulF1o/x0N0kgVUNhLG12MljCKMafTTJ8=
  app: thefinders
  on:
    repo: Finders-Master/finders-BE
